#ifndef EXIT_CODES_H_
#define EXIT_CODES_H_

#define NO_ERRORES 0
#define NO_SE_PUEDEN_RESERVAR_RECURSOS -1
#define NO_EXISTE_ARCHIVO -2
#define LEER_SIN_PERMISOS -3
#define ESCRIBIR_SIN_PERMISOS -4
#define EXCEPCION_MEMORIA -5
#define DESCONEXION_CONSOLA -6
#define FINALIZADO_CONSOLA -7
#define RESERVAR_MAS_MEMORIA_TAMANIO_PAGINA -8
#define NO_SE_PUEDEN_ASIGNAR_MAS_PAGINAS -9
#define STACK_OVERFLOW -10
#define ARCHIVO_SIN_ABRIR_PREVIAMENTE -11
#define ERROR_SINTAXIS -12
#define ARCHIVO_ABIERTO_POR_OTROS -13
#define ERROR_LEER_ARCHIVO -14
#define FINALIZADO_KERNEL -15
#define CPU_DESCONECTADO -16
//...//
#define ERROR_SIN_DEFINIR -20

#endif /* EXIT_CODES_H_ */
